
events:
  -
    title: "Ankommer Baldur's Gate"
    description: "Dere ankommer byen med flykningene"
    date: "30.04 1494 DR"
  -
    title: "Elturel forsvinner"
    description: "Hele byen forsvinner, og etterlater seg et stort krater"
    date: "20.04 1494 DR"
    image: "/timeline/h20.04.png"

characters:
  -
    name: "Blophog"
    tagline: "Bearded devil salgsmann"
    description: "Bearded devil med bare en tentakkel. Blophog er en selger"
    image: "/images/characters/blophog.png"
  -
    name: "Amrik Vanthampur"
    description: "Amrik Vanthampur ran a moneylending operation"
    image: "/images/characters/Amrik_Vanthampur_square_thumb.png"
  -
    name: "Liara Portyr"
    description: "Until recently, Liara Portyr commanded a Flaming Fist outpost called Fort Beluarian on the distant tropical peninsula of Chult. Her uncle is Duke Dillard Portyr of Baldur’s Gate, one of the city’s three remaining government leaders. Duke Portyr summoned his niece to take command of the Flaming Fist in Grand Duke Bastion Featherbottom’s absence."
    image: "/images/characters/Liara_Portyr_square_thumb.jpeg"
