
events:
  -
    title: "Ankommer Baldur's Gate"
    description: "Dere ankommer byen med flykningene"
    date: "30.04 1494 DR"
  -
    title: "Elturel forsvinner"
    description: "Hele byen forsvinner, og etterlater seg et stort krater"
    date: "20.04 1494 DR"
    image: "/timeline/h20.04.png"

characters:
  -
    name: "Amrik Vanthampur"
    description: "Amrik Vanthampur ran a moneylending operation"
    image: "https://db4sgowjqfwig.cloudfront.net/images/5567971/Amrik_Vanthampur_square_thumb.png"
  -
    title: "Elturel forsvinner"
    description: "Hele byen forsvinner, og etterlater seg et stort krater"
    date: "20.04 1494 DR"
    image: "/timeline/h20.04.png"
