
events:
  -
    title: "Ankommer Baldur's Gate"
    description: "Dere ankommer byen med flykningene"
    date: "30.04 1494 DR"
  -
    title: "Elturel forsvinner"
    description: "Hele byen forsvinner, og etterlater seg et stort krater"
    date: "20.04 1494 DR"
    image: "/timeline/h20.04.png"

characters:
  -
    name: "Blophog"
    tagline: "Bearded devil salgsmann"
    description: "Bearded devil med bare en tentakkel. Blophog er en selger"
    image: "/images/characters/blophog.png"
  -
    name: "Mad Maggie"
    tagline: "Leder for Fort Knucklebone"
    description: "Vennlig på en bestemoraktig måte. Mad Maggie er den nåværende herskeren av **Fort Knucklebone**. Hun har gjort fortet om til et handelssted for krigsherrer i Avernus.  Maggie har en drømmemaskin som kan løse opp Barts minner. Men den er ødelagt og trenger følgende deler:
    <br><br>
    **En Nirvana-tannhjulsboks**. Brukt i en rekke infernalske maskiner, disse tannhjulsboksene kommer fra Mechanus. Chukka & Clonk har en delvis montert en.<br>
    **En Hjertestein**. Brukt av nattånder for å infiltrere drømmene til sine ofre. Den brukes som et prisme eller strålesplitter.<br>
    **Phlegethosiansk sand**. Obsidiansand knust fra de kvasse, steinete slettene på Phlegethos, den fjerde laget av Helvete. Hvis Urm tårnet er der, kan du sannsynligvis få tak i den der.<br>
    **En Canian islinse**. Strålefokuserer, laget av is fra Cania, den åttende laget av Helvete. Siden den er vant til å være så kald, vil islinsene ikke vare lenge i varmen av Avernus, så når du har fått dem, må du returnere raskt.

    
    "
    image: "/images/characters/madmaggie.png"
  -
    name: "Feonor"
    tagline: "Warlord of Avernus, leder av the Golden Doom"
    description: "Tynn med melkehvite øyne, bærer en parasoll laget av bein og menneskehud"
    image: "/images/characters/feonor.png"
  -
    name: "Smiler the Defiler"
    tagline: "Eladrin ex-warlord of Avernus"
    description: "Ikke helt sikker på om han er beruset"
    image: "/images/characters/smilerthedefiler.png"
  -
    name: "Mordenkainen"
    tagline: "Trollmann"
    description: "Bor i Urm tårnet"
    image: "/images/characters/mordenkainen.pn"
  -
    name: "Red Ruth"
    tagline: "Heks"
    description: "Har en ekstra hjertestein"
    image: "/images/characters/redruth.png"

