
events:
  -
    title: "Ankommer Baldur's Gate"
    description: "Dere ankommer byen med flykningene"
    date: "30.04 1494 DR"
  -
    title: "Elturel forsvinner"
    description: "Hele byen forsvinner, og etterlater seg et stort krater"
    date: "20.04 1494 DR"
    image: "/timeline/h20.04.png"

characters:
  -
    name: "Blophog"
    tagline: "Bearded devil salgsmann"
    description: "Bearded devil med bare en tentakkel. Blophog er en selger"
    image: "/images/characters/blophog.png"
  -
    name: "Mad Maggie"
    tagline: "Leder for Fort Knucklebone"
    description: "Vennlig på en bestemoraktig måte. Mad Maggie er den nåværende herskeren av **Fort Knucklebone**. Hun har gjort fortet om til et handelssted for krigsherrer i Avernus."
    image: "/images/characters/madmaggie.png"
  -
    name: "Feonor"
    tagline: "Warlord of Avernus, leder av the Golden Doom"
    description: "Tynn med melkehvite øyne, bærer en parasoll laget av bein og menneskehud"
    image: "/images/characters/feonor.png"
  -
    name: "Smiler the Defiler"
    tagline: "Eladrin ex-warlord of Avernus"
    description: "Ikke helt sikker på om han er beruset"
    image: "/images/characters/smilerthedefiler.png"
  -
    name: "Mordenkainen"
    tagline: "Trollmann"
    description: "Bor i et tårn"
    image: ""
